// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | BackgroundImageSlice
  | AnchorSlice
  | NamePillsSlice
  | LogoRowSlice
  | LogoSlice
  | SectionTitleSlice
  | BannerSlice
  | CtaBannerSlice
  | GraphicSlice
  | EventinfoSlice
  | HeroBannerSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Settings werobot → Header navigation*
 */
export interface SettingsWerobotDocumentDataHeaderNavigationItem {
  /**
   * Label field in *Settings werobot → Header navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.header_navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings werobot → Header navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.header_navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Settings werobot → Footer navigation*
 */
export interface SettingsWerobotDocumentDataFooterNavigationItem {
  /**
   * Label field in *Settings werobot → Footer navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.footer_navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings werobot → Footer navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.footer_navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Settings werobot → Page navigation*
 */
export interface SettingsWerobotDocumentDataPageNavigationItem {
  /**
   * Label field in *Settings werobot → Page navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.page_navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings werobot → Page navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.page_navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Settings werobot documents
 */
interface SettingsWerobotDocumentData {
  /**
   * Header navigation field in *Settings werobot*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.header_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  header_navigation: prismic.GroupField<
    Simplify<SettingsWerobotDocumentDataHeaderNavigationItem>
  >;

  /**
   * Footer navigation field in *Settings werobot*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.footer_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_navigation: prismic.GroupField<
    Simplify<SettingsWerobotDocumentDataFooterNavigationItem>
  >;

  /**
   * Page navigation field in *Settings werobot*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings_werobot.page_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  page_navigation: prismic.GroupField<
    Simplify<SettingsWerobotDocumentDataPageNavigationItem>
  >;
}

/**
 * Settings werobot document from Prismic
 *
 * - **API ID**: `settings_werobot`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsWerobotDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsWerobotDocumentData>,
    "settings_werobot",
    Lang
  >;

/**
 * Item in *Site → Anchor navigation*
 */
export interface SiteDocumentDataAnchorNavigationItem {
  /**
   * Name field in *Site → Anchor navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site.anchor_navigation[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * anchor link field in *Site → Anchor navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site.anchor_navigation[].anchor_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_link: prismic.KeyTextField;
}

type SiteDocumentDataSlicesSlice =
  | AnchorSlice
  | SectionTitleSlice
  | BackgroundImageSlice
  | NamePillsSlice
  | LogoSlice
  | EventinfoSlice
  | LogoRowSlice
  | GraphicSlice
  | HeroBannerSlice
  | CtaBannerSlice
  | BannerSlice;

/**
 * Content for Site documents
 */
interface SiteDocumentData {
  /**
   * Anchor navigation field in *Site*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site.anchor_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  anchor_navigation: prismic.GroupField<
    Simplify<SiteDocumentDataAnchorNavigationItem>
  >;

  /**
   * Slice Zone field in *Site*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: site.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SiteDocumentDataSlicesSlice> /**
   * Meta Title field in *Site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: site.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: site.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Site*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: site.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Site document from Prismic
 *
 * - **API ID**: `site`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SiteDocumentData>, "site", Lang>;

export type AllDocumentTypes =
  | HomepageDocument
  | SettingsWerobotDocument
  | SiteDocument;

/**
 * Primary content in *Anchor → Default → Primary*
 */
export interface AnchorSliceDefaultPrimary {
  /**
   * anchor link field in *Anchor → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: anchor.default.primary.anchor_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_link: prismic.KeyTextField;
}

/**
 * Default variation for Anchor Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AnchorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnchorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Anchor*
 */
type AnchorSliceVariation = AnchorSliceDefault;

/**
 * Anchor Shared Slice
 *
 * - **API ID**: `anchor`
 * - **Description**: Anchor
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AnchorSlice = prismic.SharedSlice<"anchor", AnchorSliceVariation>;

/**
 * Primary content in *BackgroundImage → Default → Primary*
 */
export interface BackgroundImageSliceDefaultPrimary {
  /**
   * Image field in *BackgroundImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: background_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Position field in *BackgroundImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: background_image.default.primary.position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  position: prismic.SelectField<
    | "top-left"
    | "top-center"
    | "top-right"
    | "center-left"
    | "center"
    | "center-right"
    | "bottom-left"
    | "bottom-center"
    | "bottom-right",
    "filled"
  >;

  /**
   * Opacity field in *BackgroundImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 30
   * - **API ID Path**: background_image.default.primary.opacity
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  opacity: prismic.SelectField<"10" | "20" | "30" | "40" | "50", "filled">;

  /**
   * Size field in *BackgroundImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: medium
   * - **API ID Path**: background_image.default.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"small" | "medium" | "large" | "full", "filled">;

  /**
   * Display Mode field in *BackgroundImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: single
   * - **API ID Path**: background_image.default.primary.display_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  display_mode: prismic.SelectField<"single" | "gallery", "filled">;
}

/**
 * Primary content in *BackgroundImage → Items*
 */
export interface BackgroundImageSliceDefaultItem {
  /**
   * Image field in *BackgroundImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: background_image.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BackgroundImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BackgroundImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BackgroundImageSliceDefaultPrimary>,
  Simplify<BackgroundImageSliceDefaultItem>
>;

/**
 * Slice variation for *BackgroundImage*
 */
type BackgroundImageSliceVariation = BackgroundImageSliceDefault;

/**
 * BackgroundImage Shared Slice
 *
 * - **API ID**: `background_image`
 * - **Description**: Background overlay image with reduced brightness
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BackgroundImageSlice = prismic.SharedSlice<
  "background_image",
  BackgroundImageSliceVariation
>;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * button text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *CtaBanner → Default → Primary*
 */
export interface CtaBannerSliceDefaultPrimary {
  /**
   * Button Text field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: GET THE TICKET
   * - **API ID Path**: cta_banner.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CtaBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaBanner*
 */
type CtaBannerSliceVariation = CtaBannerSliceDefault;

/**
 * CtaBanner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: CtaBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSlice = prismic.SharedSlice<
  "cta_banner",
  CtaBannerSliceVariation
>;

/**
 * Primary content in *Eventinfo → Default → Primary*
 */
export interface EventinfoSliceDefaultPrimary {
  /**
   * Text field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eventinfo.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Alignment field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: eventinfo.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"center" | "left" | "right", "filled">;

  /**
   * Show shadow field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: eventinfo.default.primary.show_shadow
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_shadow: prismic.BooleanField;

  /**
   * Graphic image field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventinfo.default.primary.graphic_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  graphic_image: prismic.ImageField<never>;

  /**
   * Graphic position field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: absolute-top-right
   * - **API ID Path**: eventinfo.default.primary.graphic_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  graphic_position: prismic.SelectField<
    | "absolute-top-left"
    | "absolute-top-middle"
    | "absolute-top-right"
    | "absolute-left-middle"
    | "absolute-right-middle"
    | "absolute-bottom-left"
    | "absolute-bottom-middle"
    | "absolute-bottom-right",
    "filled"
  >;

  /**
   * Graphic size field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: small
   * - **API ID Path**: eventinfo.default.primary.graphic_size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  graphic_size: prismic.SelectField<"small" | "medium" | "large", "filled">;

  /**
   * Graphic image 2 field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventinfo.default.primary.graphic_image_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  graphic_image_2: prismic.ImageField<never>;

  /**
   * Graphic position 2 field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: absolute-bottom-left
   * - **API ID Path**: eventinfo.default.primary.graphic_position_2
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  graphic_position_2: prismic.SelectField<
    | "absolute-top-left"
    | "absolute-top-middle"
    | "absolute-top-right"
    | "absolute-left-middle"
    | "absolute-right-middle"
    | "absolute-bottom-left"
    | "absolute-bottom-middle"
    | "absolute-bottom-right",
    "filled"
  >;

  /**
   * Graphic size 2 field in *Eventinfo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: small
   * - **API ID Path**: eventinfo.default.primary.graphic_size_2
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  graphic_size_2: prismic.SelectField<"small" | "medium" | "large", "filled">;
}

/**
 * Default variation for Eventinfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventinfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventinfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Eventinfo*
 */
type EventinfoSliceVariation = EventinfoSliceDefault;

/**
 * Eventinfo Shared Slice
 *
 * - **API ID**: `eventinfo`
 * - **Description**: Eventinfo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventinfoSlice = prismic.SharedSlice<
  "eventinfo",
  EventinfoSliceVariation
>;

/**
 * Primary content in *Graphic → Default → Primary*
 */
export interface GraphicSliceDefaultPrimary {
  /**
   * Graphic image field in *Graphic → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: graphic.default.primary.graphic_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  graphic_image: prismic.ImageField<never>;

  /**
   * Position field in *Graphic → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: graphic.default.primary.position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  position: prismic.SelectField<
    | "center"
    | "absolute-left"
    | "absolute-right"
    | "absolute-top-left"
    | "absolute-top-middle"
    | "absolute-top-right"
    | "absolute-left-middle"
    | "absolute-right-middle"
    | "absolute-bottom-left"
    | "absolute-bottom-middle"
    | "absolute-bottom-right"
    | "float-left"
    | "float-right",
    "filled"
  >;

  /**
   * Alignment field in *Graphic → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: graphic.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"center" | "left" | "right", "filled">;

  /**
   * Size field in *Graphic → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: small
   * - **API ID Path**: graphic.default.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"small" | "medium" | "large", "filled">;
}

/**
 * Default variation for Graphic Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GraphicSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GraphicSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Graphic*
 */
type GraphicSliceVariation = GraphicSliceDefault;

/**
 * Graphic Shared Slice
 *
 * - **API ID**: `graphic`
 * - **Description**: Graphic
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GraphicSlice = prismic.SharedSlice<
  "graphic",
  GraphicSliceVariation
>;

/**
 * Primary content in *Herotext → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Title field in *Herotext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: WeRobot 2026
   * - **API ID Path**: hero_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for Herotext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Herotext*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * Herotext Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *Logo → Default → Primary*
 */
export interface LogoSliceDefaultPrimary {
  /**
   * LOGO  field in *Logo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * TEXT  field in *Logo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: TRALIALIA
   * - **API ID Path**: logo.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Desktop offset X (px) field in *Logo → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: e.g. 80
   * - **API ID Path**: logo.default.primary.desktop_offset_x
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  desktop_offset_x: prismic.NumberField;

  /**
   * Desktop offset Y (px) field in *Logo → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: e.g. 120
   * - **API ID Path**: logo.default.primary.desktop_offset_y
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  desktop_offset_y: prismic.NumberField;

  /**
   * Desktop width (px) field in *Logo → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: e.g. 320
   * - **API ID Path**: logo.default.primary.desktop_width
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  desktop_width: prismic.NumberField;

  /**
   * Layer order (z-index) field in *Logo → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Higher numbers appear on top
   * - **API ID Path**: logo.default.primary.z_index
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  z_index: prismic.NumberField;

  /**
   * Rotation (degrees) field in *Logo → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: e.g. -5
   * - **API ID Path**: logo.default.primary.rotation
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rotation: prismic.NumberField;
}

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault;

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoSlice = prismic.SharedSlice<"logo", LogoSliceVariation>;

/**
 * Item in *LogoRow → Default → Primary → LOGO*
 */
export interface LogoRowSliceDefaultPrimaryLogoItem {
  /**
   * logo field in *LogoRow → Default → Primary → LOGO*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_row.default.primary.logo[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *LogoRow → Default → Primary*
 */
export interface LogoRowSliceDefaultPrimary {
  /**
   * LOGO field in *LogoRow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_row.default.primary.logo[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logo: prismic.GroupField<Simplify<LogoRowSliceDefaultPrimaryLogoItem>>;
}

/**
 * Default variation for LogoRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoRowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LogoRow*
 */
type LogoRowSliceVariation = LogoRowSliceDefault;

/**
 * LogoRow Shared Slice
 *
 * - **API ID**: `logo_row`
 * - **Description**: LogoRow
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoRowSlice = prismic.SharedSlice<
  "logo_row",
  LogoRowSliceVariation
>;

/**
 * Item in *NamePills → Default → Primary → pills*
 */
export interface NamePillsSliceDefaultPrimaryPillsItem {
  /**
   * Text field in *NamePills → Default → Primary → pills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pills.default.primary.pills[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *NamePills → Default → Primary → pills*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pills.default.primary.pills[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *NamePills → Default → Primary*
 */
export interface NamePillsSliceDefaultPrimary {
  /**
   * section_title field in *NamePills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pills.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Layout field in *NamePills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: wrap
   * - **API ID Path**: name_pills.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  layout: prismic.SelectField<"wrap" | "columns", "filled">;

  /**
   * pills field in *NamePills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: name_pills.default.primary.pills[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pills: prismic.GroupField<Simplify<NamePillsSliceDefaultPrimaryPillsItem>>;
}

/**
 * Default variation for NamePills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NamePillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NamePillsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NamePills*
 */
type NamePillsSliceVariation = NamePillsSliceDefault;

/**
 * NamePills Shared Slice
 *
 * - **API ID**: `name_pills`
 * - **Description**: NamePills
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NamePillsSlice = prismic.SharedSlice<
  "name_pills",
  NamePillsSliceVariation
>;

/**
 * Primary content in *SectionTitle → Default → Primary*
 */
export interface SectionTitleSliceDefaultPrimary {
  /**
   * title field in *SectionTitle → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: HOSTING ORGANISATIONS
   * - **API ID Path**: section_title.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for SectionTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionTitle*
 */
type SectionTitleSliceVariation = SectionTitleSliceDefault;

/**
 * SectionTitle Shared Slice
 *
 * - **API ID**: `section_title`
 * - **Description**: SectionTitle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionTitleSlice = prismic.SharedSlice<
  "section_title",
  SectionTitleSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsWerobotDocument,
      SettingsWerobotDocumentData,
      SettingsWerobotDocumentDataHeaderNavigationItem,
      SettingsWerobotDocumentDataFooterNavigationItem,
      SettingsWerobotDocumentDataPageNavigationItem,
      SiteDocument,
      SiteDocumentData,
      SiteDocumentDataAnchorNavigationItem,
      SiteDocumentDataSlicesSlice,
      AllDocumentTypes,
      AnchorSlice,
      AnchorSliceDefaultPrimary,
      AnchorSliceVariation,
      AnchorSliceDefault,
      BackgroundImageSlice,
      BackgroundImageSliceDefaultPrimary,
      BackgroundImageSliceDefaultItem,
      BackgroundImageSliceVariation,
      BackgroundImageSliceDefault,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      CtaBannerSlice,
      CtaBannerSliceDefaultPrimary,
      CtaBannerSliceVariation,
      CtaBannerSliceDefault,
      EventinfoSlice,
      EventinfoSliceDefaultPrimary,
      EventinfoSliceVariation,
      EventinfoSliceDefault,
      GraphicSlice,
      GraphicSliceDefaultPrimary,
      GraphicSliceVariation,
      GraphicSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      LogoSlice,
      LogoSliceDefaultPrimary,
      LogoSliceVariation,
      LogoSliceDefault,
      LogoRowSlice,
      LogoRowSliceDefaultPrimaryLogoItem,
      LogoRowSliceDefaultPrimary,
      LogoRowSliceVariation,
      LogoRowSliceDefault,
      NamePillsSlice,
      NamePillsSliceDefaultPrimaryPillsItem,
      NamePillsSliceDefaultPrimary,
      NamePillsSliceVariation,
      NamePillsSliceDefault,
      SectionTitleSlice,
      SectionTitleSliceDefaultPrimary,
      SectionTitleSliceVariation,
      SectionTitleSliceDefault,
    };
  }
}
