// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  eventinfo: dynamic(() => import("./Eventinfo")),
  graphic: dynamic(() => import("./Graphic")),
  hero_banner: dynamic(() => import("./Herotext")),
};
