// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  anchor: dynamic(() => import("./Anchor")),
  background_image: dynamic(() => import("./BackgroundImage")),
  banner: dynamic(() => import("./Banner")),
  cta_banner: dynamic(() => import("./CtaBanner")),
  eventinfo: dynamic(() => import("./Eventinfo")),
  graphic: dynamic(() => import("./Graphic")),
  hero_banner: dynamic(() => import("./Herotext")),
  logo: dynamic(() => import("./Logo")),
  logo_row: dynamic(() => import("./LogoRow")),
  name_pills: dynamic(() => import("./NamePills")),
  section_title: dynamic(() => import("./SectionTitle")),
};
