// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  cta_banner: dynamic(() => import("./CtaBanner")),
  eventinfo: dynamic(() => import("./Eventinfo")),
  graphic: dynamic(() => import("./Graphic")),
  hero_banner: dynamic(() => import("./Herotext")),
  logo: dynamic(() => import("./Logo")),
  logo_row: dynamic(() => import("./LogoRow")),
  section_title: dynamic(() => import("./SectionTitle")),
};
